ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root
WORKDIR /app

COPY --chown=node:node package.json package-lock.json ./
RUN npm ci --omit=dev && chown -R node:node /app/node_modules

COPY --chown=node:node server.mjs ./
COPY --chown=node:node lib ./lib

USER node
